#include "AICharacterBase.h"

AAICharacterBase::AAICharacterBase(const FObjectInitializer& ObjectInitializer) 
	: Super(ObjectInitializer) 
{
	PrimaryActorTick.bCanEverTick = true;
}

void AAICharacterBase::BeginPlay()
{
	Super::BeginPlay();
	
	// Most likely generated by unreal template Character file
}